// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTi6Yg2B3Q4bHgOGO5tTQPIQ6TlMl30_s',
    appId: '1:570406554758:web:bda4a3ff60638fc5f9d507',
    messagingSenderId: '570406554758',
    projectId: 'bitlearn-1fc4b',
    authDomain: 'bitlearn-1fc4b.firebaseapp.com',
    storageBucket: 'bitlearn-1fc4b.appspot.com',
    measurementId: 'G-WMT3TPSZJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDin6wUrVRKGMNtMcCH-HYnM-8nBaqqJw',
    appId: '1:570406554758:android:a130086a898c92eaf9d507',
    messagingSenderId: '570406554758',
    projectId: 'bitlearn-1fc4b',
    storageBucket: 'bitlearn-1fc4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBIvwjiog3JSFa_d4F6olQQOjL1VtEUCM',
    appId: '1:570406554758:ios:bc0c31bda299653ff9d507',
    messagingSenderId: '570406554758',
    projectId: 'bitlearn-1fc4b',
    storageBucket: 'bitlearn-1fc4b.appspot.com',
    iosClientId: '570406554758-f77t9dqkn9hurp0g9lqagrqqrgn385a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitbybit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBIvwjiog3JSFa_d4F6olQQOjL1VtEUCM',
    appId: '1:570406554758:ios:bc0c31bda299653ff9d507',
    messagingSenderId: '570406554758',
    projectId: 'bitlearn-1fc4b',
    storageBucket: 'bitlearn-1fc4b.appspot.com',
    iosClientId: '570406554758-f77t9dqkn9hurp0g9lqagrqqrgn385a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitbybit',
  );
}
